[www]
; 谁可以运行这个服务
user = www-data
group = www-data

; 【核心关键】：监听 9000 端口，接收来自 Nginx 的请求
listen = 9000

; 允许连接到 PHP-FPM 的用户/权限控制
listen.owner = www-data
listen.group = www-data

; 进程管理模式（动态创建进程）
pm = dynamic
pm.max_children = 25
pm.start_servers = 5
pm.min_spare_servers = 2
pm.max_spare_servers = 10